### ISSUE TITLE
Requested module experienced an error while loading - [BUG]

### ISSUE THREAD

**Issue by emeraldongithub** [CitizenFoffie/ob-framework#2]
**Describe the bug**
  "17:01:25.973  Requested module experienced an error while loading  -  Server - Script:1"
--Output

**To Reproduce**

**Expected behavior**
Load the framework after putting "require(script.Parent:WaitForChild("MainModule")):Load("2014M")" in an empty script on ServerScriptService like what it told me
**Screenshots**
![image](https://user-images.githubusercontent.com/99167692/218415805-95f0b854-85ab-45dc-9da5-4601cb369892.png)
![image](https://user-images.githubusercontent.com/99167692/218415843-79d3ec34-af20-4eea-a60b-aab3d2503339.png)
![image](https://user-images.githubusercontent.com/99167692/218415861-8777b737-e1d4-47e3-8131-32193cf6bd38.png)

**Desktop (please complete the following information):**
 - Framework Version: [e.g. v1.6.3]

**Additional context**

**Comment by Komodo794** [comment]
Did you by any chance rename the loader? @emeraldongithub

**Comment by emeraldongithub** [comment]
No but I found out why it wasn’t working
I loaded it on an old place

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Komodo794** [comment]
make sure you are loading it like this

**local obFramework = require(script.Parent:WaitForChild("MainModule"))

obFramework:Load("2015E")**

also make sure your game is set in R6

**Comment by Komodo794** [comment]
oh, i didn't see your message you sent me, my bad

**Comment by CitizenFoffie** [comment]
Solved

**Comment by Andypizza647** [comment]
i might be late to this (if so well sorry then), but it sometimes might (also) be due to the SoundService
being named "Soundscape" instead due to the nature of old roblox games being different
from now a days roblox, anyways just change renaming "Soundscape" To "SoundService" might fix the problem i think.

**Comment by PizzaLuigi647** [comment]
i might be late to this (if so well sorry then), but it sometimes might (also) be due to the SoundService
being named "Soundscape" in (most) old roblox games instead due to the nature of old roblox games being different
from now a days roblox, anyways just change renaming "Soundscape" To "SoundService" might fix the problem i think.
